apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: /api/v1
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
