# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
# the control plane node config
- role: control-plane
  image: kindest/node:v1.15.0
# the three workers
- role: worker
  image: kindest/node:v1.15.0
- role: worker
  image: kindest/node:v1.15.0
