#!/env/python

"""
Script used to parse statisctis usage collected by
docker stats and statisctis generated by logger
stored in tmp direcory
"""


PARSE_LOG_FILE = False

USAGE_DATA_PATH = 'output/usage.txt'

LOG_FILE_PATH = '/tmp/log.txt'

NUMBER_OF_NDOES = 3

result = {}

with open(USAGE_DATA_PATH) as f:
    l = f.readlines()
    counter = 0
    date = ''
    for entry in l:
        entry = entry.rstrip('\n')
        if counter == 0:
            date = entry
            counter += 1
            continue

        part = entry.split(' ')[1] # 213GiB
        number = float(part[:-3]) # 213
        node_name = entry.split(' ')[0]

        if part[-3:] == 'GiB':
            number *= 1000

        res = node_name + ' ' + str(number)
        record = date + ' ' + res

        print (record)

        if entry.split(' ')[0] not in result:
            result[entry.split(' ')[0]] = []

        result[entry.split(' ')[0]].append(record)

        counter += 1
        if counter == NUMBER_OF_NDOES + 1:
            counter = 0

for record in result:
    filename = 'output/' + record
    with open(filename, 'w') as file:
        for el in result[record]:
            file.write(el)
            file.write('\n')

if (PARSE_LOG_FILE):
    result = {}
    # parse logger file
    with open(LOG_FILE_PATH) as f:
        l = f.readlines()
        i = 0

        for entry in l:
            entry = entry.rstrip('\n')

            if i == 0:
                for i in range(4,len(entry.split(':'))):
                    result[entry.split(':')[i]] = []
                i += 1
                continue

            date = entry[0:19]
            rest = entry.split(':')[4]
            node_name = rest.split(' ')[0]
            node_usage = rest.split(' ')[1] + 'Ki'
            result[node_name].append(date + ' ' + node_usage)

    for record in result:
        filename = 'output/' + record + '_logger'
        with open(filename, 'w') as file:
            for el in result[record]:
                file.write(el)
                file.write('\n')
