pods_paramsusage = [
"""{"metadata": {"generate_name": "test_pod_1",
              "labels": {"k8s-app": "kube-dns",
                         "pod-template-hash": "5c98db65d4"}},
 "spec": {"affinity": "None",
          "node_name": "control-plane",
          "scheduler_name": "default-scheduler",
          "containers": [{"name": "container_1",
                          "resources": {"limits": {"memory": "170Mi"},
                                        "requests": {"cpu": "100m",
                                                     "memory": "70Mi"}}
                          "usage": {"cpu": "500000n", "memory": "9000Ki"}}],
          "tolerations": [{"effect": "None",
                           "key": "CriticalAddonsOnly",
                           "operator": "Exists",
                           "toleration_seconds": "None",
                           "value": "None"},
                          {"effect": "NoSchedule",
                           "key": "node-role.kubernetes.io/master",
                           "operator": "None",
                           "toleration_seconds": "None",
                           "value": "None"},
                          {"effect": "NoExecute",
                           "key": "node.kubernetes.io/not-ready",
                           "operator": "Exists",
                           "toleration_seconds": 300,
                           "value": "None"},
                          {"effect": "NoExecute",
                           "key": "node.kubernetes.io/unreachable",
                           "operator": "Exists",
                           "toleration_seconds": 300,
                           "value": "None"}]},
 "status": {"phase": "Running"}}""",
 ]
