apiVersion: apps/v1
kind: Deployment
metadata:
  name: costum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: costum
  template:
    metadata:
      labels:
        app: costum
    spec:
      schedulerName: custom_scheduler
      containers:
      - name: costum
        image: paulbouwer/hello-kubernetes:1.5
