apiVersion: apps/v1
kind: Deployment
metadata:
  name: twentymb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twentymb
  template:
    metadata:
      labels:
        app: twentymb
    spec:
      schedulerName: foobar
      containers:
      - name: twentymb
        image: paulbouwer/hello-kubernetes:1.5
        resources:
          requests:
            memory: "m"
          limits:
            memory: "10m"
