apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-2
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      schedulerName: my_scheduler
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
       resources:
         requests:
           memory: "300Mi"
          limits:
            memory: "50M"
