apiVersion: apps/v1
kind: Deployment
metadata:
  name: load2
  labels:
    app: load2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load2
  template:
    metadata:
      labels:
        app: load2
    spec:
      schedulerName: "abc-scheduler"
      containers:
        - name: abc
          image: load:0.1
          imagePullPolicy: Never
          # resources:
            # requests:
              # memory: "250Mi"
            # # limits:
            # #   memory: "3000Mi"
