apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
  namespace: kube-system
  labels:
    app: foobar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar
  template:
    metadata:
      labels:
        app: foobar
    spec:
      containers:
        - name: foobar
          image: scheduler:1288c28
          imagePullPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: kind-control-plane
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
          operator: "Exists"
