apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo02
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo02
  template:
    metadata:
      labels:
        app: foo02
    spec:
      schedulerName: my_scheduler
      containers:
      - name: foo02
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
          limits:
            memory: "500M"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo01
spec:
  replicas: 6
  selector:
    matchLabels:
      app: foo01
  template:
    metadata:
      labels:
        app: foo01
    spec:
      schedulerName: my_scheduler
      containers:
      - name: foo01
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
